name: Docker Build and Push

on:
  push:
    tags: ['v*.*.*']
  pull_request:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=tag,value=latest

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: BUILDKIT_PROGRESS=plain,NPM_CONFIG_LOGLEVEL=verbose,NPM_CONFIG_REGISTRY=https://registry.npmjs.org/
          outputs: type=oci,dest=/tmp/myimage.tar

      - name: Display npm logs if build fails
        if: failure()
        run: |
          docker run --rm -v "/var/run/docker.sock:/var/run/docker.sock" -v "$PWD:/workspace" --workdir /workspace ubuntu tail -n 100 /workspace/root/.npm/_logs/*.log || echo "No logs found or permission denied"

      - name: Load built Docker image
        if: success()
        run: |
          docker load -i /tmp/myimage.tar
          docker images
