name: Docker

on:
  push:
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=tag,value=latest

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: BUILDKIT_PROGRESS=plain,NPM_CONFIG_LOGLEVEL=verbose
          outputs: type=oci,dest=/tmp/myimage.tar

      - name: Archive Docker build logs
        uses: actions/upload-artifact@v2
        with:
          name: docker-build-logs
          path: /tmp/myimage.tar
          if-no-files-found: error # Change this to 'warn' or 'ignore' if you do not want the job to fail

      # Optional: If you need to do something with the built image locally
      - name: Load built Docker image
        if: github.event_name == 'pull_request'
        run: |
          docker load -i /tmp/myimage.tar
          docker images

      # Additional steps like deploying or testing could go here
